FROM php:8.2-fpm

# Set working directory
WORKDIR /var/www/app

# Install system dependencies (as root)
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zlib1g-dev \
    zip \
    unzip \
    jpegoptim \
    optipng \
    pngquant \
    gifsicle \
    locales

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions (as root)
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Install Composer (as root)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create user and group (as root)
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

RUN chown www:www /var/www/app

# Copy existing application directory contents
# Copy all files and set ownership to www:www
COPY --chown=www:www . /var/www/app

# Set correct permissions for storage and bootstrap/cache
# We do this as root *before* switching to the www user
RUN chgrp -R www storage bootstrap/cache \
    && chmod -R ug+w storage bootstrap/cache
# -----------------------

# Switch to the non-privileged user
USER www

# Install dependencies (as www user)
# Now, the post-install scripts will have write permissions
RUN composer install

# Expose port 9000 for PHP-FPM
EXPOSE 9000

CMD ["php-fpm"]
